version: '3.8'

services:
  app:
    image: chat-service
    container_name: chat-service
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_URL=db:3306
      - DB_DATABASE=chat-service
    ports:
      - "8080:8080"
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-service
    ports:
      - "3306:3306"  
    expose:
      - "3306"
    networks:
      - app_network
    volumes:
      - data-db:/var/lib/mysql
      - ./dump-chat-service-202408261708.sql:/docker-entrypoint-initdb.d/dump-chat-service-202408261708.sql

volumes:
  data-db:

networks:
  app_network:
    driver: bridge
